server:
  port: 8181

spring:
  application:
    name: es-sample
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9300
      repositories:
        enabled: true